# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install packages
        run: sudo apt install -y wget git cmake gcc g++ 
      - name: bintray setup
        run: |
              wget https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_31_2.deb
              sudo dpkg -i conan-ubuntu-64_1_31_2.deb
              conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 

      # Runs a set of commands using the runners shell
      - name: build & run
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          ./bin/graphyQmlFileSelectorModuleApp
